custom:
  site:
    name: "COMMARS"
    cookieDomain: "${custom.prod.cookieDomain}"
    frontUrl: "${custom.prod.frontUrl}"
    backUrl: "${custom.prod.backUrl}"

server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/deploy_test
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver