spring:
  datasource:
    url: jdbc:mysql://likelion-mars-mysql.cvi8qmy2a7zg.ap-northeast-2.rds.amazonaws.com/likelion_mars
    username: root
    password: likelion123
    driver-class-name: com.mysql.cj.jdbc.Driver